import { useMemo, useState } from "react";
import { useGame } from "@/app/GameContext";
import { activeBody, unlockedItemsForApp } from "@/content/selectors";
import { appById } from "@/content/content-pack";

type AnyBody=Record<string,unknown>;
function describe(body:AnyBody):string { return String(body.text??body.title??body.subject??body.merchant??body.track??body.name??body.city??body.label??body.question??body.author??body.from??body.route??body.heading??"可交互内容"); }
export function GenericApp({appId}:{appId:string}) { const {state,setUiFlag}=useGame(); const [selected,setSelected]=useState<string|null>(null); const [active,setActive]=useState(false); const items=unlockedItemsForApp(state,appId); const app=appById.get(appId); const selectedItem=items.find(i=>i.id===selected); const bodies=useMemo(()=>items.map(i=>[i,activeBody(state,i) as AnyBody] as const),[items,state]); if(selectedItem){const b=activeBody(state,selectedItem) as AnyBody;return <div className="generic-detail"><button className="inline-back" onClick={()=>setSelected(null)}>‹ {app?.displayName}</button><h2>{describe(b)}</h2><dl>{Object.entries(b).filter(([,v])=>typeof v!=="object").map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl><button className={`primary-action ${active?"active":""}`} onClick={()=>{setActive(v=>!v);setUiFlag(`${appId}.interaction`,!active)}}>{active?"已完成一次有效交互":"执行一次有效交互"}</button></div>}
 return <div className="generic-app"><div className="generic-banner"><b>{app?.displayName}</b><span>{app?.tier}级交互 · 本地模拟账号</span></div><div className="list">{bodies.map(([i,b])=><button className="list-row" data-testid="app-effective-action" key={i.id} onClick={()=>setSelected(i.id)}><span className="avatar">{app?.displayName.slice(0,1)}</span><span><b>{describe(b)}</b><small>{i.narrative.firstReadValue}</small></span></button>)}{items.length===0&&<button className="primary-action" data-testid="app-effective-action" onClick={()=>setActive(v=>!v)}>{active?"状态已切换":"切换一个真实功能状态"}</button>}</div></div>; }
