import { useMemo, useState } from "react";
import { useGame } from "@/app/GameContext";
import { activeBody, unlockedItemsForApp } from "@/content/selectors";
import { appById } from "@/content/content-pack";
import { isQaMode } from "@/lib/qa-mode";

type AnyBody=Record<string,unknown>;
function describe(body:AnyBody):string { return String(body.text??body.title??body.subject??body.merchant??body.track??body.name??body.city??body.label??body.question??body.author??body.from??body.route??body.heading??"可交互内容"); }
export function GenericApp({appId}:{appId:string}) { const {state,emit}=useGame(); const [selected,setSelected]=useState<string|null>(null); const [active,setActive]=useState(false); const items=unlockedItemsForApp(state,appId); const app=appById.get(appId); const selectedItem=items.find(i=>i.id===selected); const bodies=useMemo(()=>items.map(i=>[i,activeBody(state,i) as AnyBody] as const),[items,state]); const qaMode=isQaMode(); if(selectedItem){const b=activeBody(state,selectedItem) as AnyBody;return <div className="generic-detail"><button className="inline-back" onClick={()=>setSelected(null)}>‹ {app?.displayName}</button><h2>{describe(b)}</h2><dl>{Object.entries(b).filter(([,v])=>typeof v!=="object").map(([k,v])=><div key={k}><dt>{qaMode?k:""}</dt><dd>{String(v)}</dd></div>)}</dl><button className={`primary-action ${active?"active":""}`} onClick={()=>{setActive(v=>!v);emit("content.item.interacted",selectedItem.id,{active:!active})}}>{active?"已保存":"保存"}</button></div>}
 return <div className="generic-app">{qaMode&&<div className="generic-banner"><b>{app?.displayName}</b><span>{app?.tier}级交互 · 本地模拟账号</span></div>}<div className="list">{bodies.map(([i,b])=><button className="list-row" data-testid="app-effective-action" key={i.id} onClick={()=>{setSelected(i.id);emit("content.item.opened",i.id,{appId})}}><span className="avatar">{app?.displayName.slice(0,1)}</span><span><b>{describe(b)}</b><small>{i.narrative.firstReadValue}</small></span></button>)}{items.length===0&&<button className="primary-action" data-testid="app-effective-action" onClick={()=>{setActive(v=>!v);emit("app.generic.interacted",appId,{active:!active})}}>{active?"已更新":"刷新"}</button>}</div></div>; }
